server: 
  port: 9527
 
spring: 
  application:
    name: microservicexw-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
  #ignored-services: microservicexw-dept
  prefix: /atxiaowei
  ignored-services: "*"
  routes: 
    mydept.serviceId: microservicexw-dept
    mydept.path: /mydept/**
 
info:
  app.name: atxiaowei-microcloud
  company.name: www.atxiaowei.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

